name: Node.js CI

on:
  schedule:
    - cron:  '30 4 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm start
      - name: Commit detected changes
        uses: EndBug/add-and-commit@v9
        with:
          add: '["manifest.json","catalog"]'
          author_name: "Victor Guerra Veloso"
          author_email: "victorgvbh@gmail.com"
          default_author: user_info
          new_branch: main
          message: "Github actions updated anime season data"
          push: "origin main --set-upstream --force"